-- MySQL Script generated by MySQL Workbench
-- Thu 13 Dec 2018 11:01:40 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jc_concepts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jc_concepts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jc_concepts` DEFAULT CHARACTER SET latin1 ;
USE `jc_concepts` ;

-- -----------------------------------------------------
-- Table `jc_concepts`.`physical_properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`physical_properties` (
  `physical_properties_id` INT(11) NOT NULL AUTO_INCREMENT,
  `length` DECIMAL(5,2) NOT NULL,
  `width` DECIMAL(5,2) NOT NULL,
  `height` DECIMAL(5,2) NOT NULL,
  `geometry` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`physical_properties_id`),
  UNIQUE INDEX `physical_properties_id_UNIQUE` (`physical_properties_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jc_concepts`.`style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`style` (
  `style_id` INT(11) NOT NULL AUTO_INCREMENT,
  `style_description` TEXT NOT NULL,
  `style_name` VARCHAR(45) NOT NULL,
  `style_year` YEAR(4) NOT NULL,
  PRIMARY KEY (`style_id`),
  UNIQUE INDEX `style_name_UNIQUE` (`style_name` ASC),
  UNIQUE INDEX `style_id_UNIQUE` (`style_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jc_concepts`.`picture_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`picture_album` (
  `picture_album_id` INT NOT NULL AUTO_INCREMENT,
  `pic_cover` VARCHAR(45) NOT NULL,
  `pic_front` VARCHAR(45) NOT NULL,
  `pic_side` VARCHAR(45) NOT NULL,
  `pic_back` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`picture_album_id`),
  UNIQUE INDEX `picture_album_id_UNIQUE` (`picture_album_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jc_concepts`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(20) NOT NULL,
  `product_price` DECIMAL(7,2) NOT NULL,
  `product_description` TINYTEXT NOT NULL,
  `product_pop` INT(11) NOT NULL DEFAULT 0,
  `product_rating` DECIMAL(2,1) NOT NULL DEFAULT 0,
  `product_created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `product_featured` TINYINT(1) NOT NULL,
  `product_mode` TINYINT(1) NOT NULL,
  `location_name` ENUM('Kitchen', 'Living Room', 'Bedroom', 'Patio', 'Backyard', 'TV Room', 'Garage') NOT NULL,
  `style_id` INT(11) NOT NULL,
  `picture_album_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_s` (`style_id` ASC),
  INDEX `fk_product_picture_album1_idx` (`picture_album_id` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  UNIQUE INDEX `picture_album_id_UNIQUE` (`picture_album_id` ASC),
  UNIQUE INDEX `product_name_UNIQUE` (`product_name` ASC),
  CONSTRAINT `fk_s`
    FOREIGN KEY (`style_id`)
    REFERENCES `jc_concepts`.`style` (`style_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_picture_album1`
    FOREIGN KEY (`picture_album_id`)
    REFERENCES `jc_concepts`.`picture_album` (`picture_album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`furniture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`furniture` (
  `product_id` INT(11) NOT NULL,
  `furniture_type` ENUM('Armoire', 'Bar', 'Barstool', 'Bed Frame', 'Bench', 'Bookcase', 'Chair', 'Desk', 'Cocktail Table', 'Nightstand', 'Table') NOT NULL,
  `physical_properties_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `fk_f` (`product_id` ASC),
  INDEX `fk_furniture_physical_properties1_idx` (`physical_properties_id` ASC),
  CONSTRAINT `fk_furniture_physical_properties1`
    FOREIGN KEY (`physical_properties_id`)
    REFERENCES `jc_concepts`.`physical_properties` (`physical_properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_furniture_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `jc_concepts`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jc_concepts`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`material` (
  `material_id` INT(11) NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(20) NOT NULL,
  `material_description` TINYTEXT NOT NULL,
  `material_cost_per_unit` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`material_id`),
  UNIQUE INDEX `material_name_UNIQUE` (`material_name` ASC),
  UNIQUE INDEX `material_id_UNIQUE` (`material_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jc_concepts`.`pp_h_m`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`pp_h_m` (
  `physical_properties_id` INT(11) NOT NULL,
  `material_id` INT(11) NOT NULL,
  PRIMARY KEY (`physical_properties_id`, `material_id`),
  INDEX `fk_m1` (`material_id` ASC),
  INDEX `fk_pp` (`physical_properties_id` ASC),
  CONSTRAINT `fk_m1`
    FOREIGN KEY (`material_id`)
    REFERENCES `jc_concepts`.`material` (`material_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pp1`
    FOREIGN KEY (`physical_properties_id`)
    REFERENCES `jc_concepts`.`physical_properties` (`physical_properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jc_concepts`.`room_floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`room_floor` (
  `room_floor_id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_floor_description` TINYTEXT NOT NULL,
  `room_floor_style` ENUM('Mosaic', 'Solid', 'Planks') NOT NULL,
  PRIMARY KEY (`room_floor_id`),
  UNIQUE INDEX `room_floor_id_UNIQUE` (`room_floor_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`room` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_total_area` DECIMAL(6,2) NOT NULL,
  `room_floor_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_room_room_floor1_idx` (`room_floor_id` ASC),
  UNIQUE INDEX `product_type_id_UNIQUE` (`product_id` ASC),
  CONSTRAINT `fk_room_room_floor1`
    FOREIGN KEY (`room_floor_id`)
    REFERENCES `jc_concepts`.`room_floor` (`room_floor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `jc_concepts`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`room_component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`room_component` (
  `room_component_id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_component_name` VARCHAR(45) NOT NULL,
  `room_component_description` TINYTEXT NOT NULL,
  `room_component_type` ENUM('Shelf', 'Cabinet', 'Door', 'Bar', 'Counter', 'Microwave Cabinet', 'Fridge Cabinet', 'Pantry') NOT NULL,
  `physical_properties_id` INT(11) NOT NULL,
  PRIMARY KEY (`room_component_id`),
  INDEX `fk_room_component_physical_properties1_idx` (`physical_properties_id` ASC),
  UNIQUE INDEX `room_component_id_UNIQUE` (`room_component_id` ASC),
  UNIQUE INDEX `room_component_name_UNIQUE` (`room_component_name` ASC),
  CONSTRAINT `fk_room_component_physical_properties1`
    FOREIGN KEY (`physical_properties_id`)
    REFERENCES `jc_concepts`.`physical_properties` (`physical_properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`r_h_rc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`r_h_rc` (
  `product_id` INT(11) NOT NULL,
  `room_component_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `room_component_id`),
  INDEX `fk_rc` (`room_component_id` ASC),
  INDEX `fk_r` (`product_id` ASC),
  CONSTRAINT `fk_r`
    FOREIGN KEY (`product_id`)
    REFERENCES `jc_concepts`.`room` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rc`
    FOREIGN KEY (`room_component_id`)
    REFERENCES `jc_concepts`.`room_component` (`room_component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`promotion` (
  `promotion_id` INT(11) NOT NULL AUTO_INCREMENT,
  `promotion_name` VARCHAR(45) NOT NULL,
  `promotion_description` TINYTEXT NOT NULL,
  `promotion_picture` VARCHAR(45) NOT NULL,
  `promotion_price_modifier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`promotion_id`),
  UNIQUE INDEX `promotion_id_UNIQUE` (`promotion_id` ASC),
  UNIQUE INDEX `promotion_name_UNIQUE` (`promotion_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jc_concepts`.`php`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`php` (
  `product_id` INT(11) NOT NULL,
  `promotion_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `promotion_id`),
  INDEX `fk_phpromprom1` (`promotion_id` ASC),
  INDEX `fk_phpromp1_idx` (`product_id` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  CONSTRAINT `fk_phpromp`
    FOREIGN KEY (`product_id`)
    REFERENCES `jc_concepts`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phpromprom1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `jc_concepts`.`promotion` (`promotion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`rf_h_m`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`rf_h_m` (
  `room_floor_id` INT(11) NOT NULL,
  `material_id` INT(11) NOT NULL,
  PRIMARY KEY (`room_floor_id`, `material_id`),
  INDEX `fk_room_floor_has_material_material1_idx` (`material_id` ASC),
  INDEX `fk_room_floor_has_material_room_floor1_idx` (`room_floor_id` ASC),
  CONSTRAINT `fk_room_floor_has_material_room_floor1`
    FOREIGN KEY (`room_floor_id`)
    REFERENCES `jc_concepts`.`room_floor` (`room_floor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_floor_has_material_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `jc_concepts`.`material` (`material_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jc_concepts`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password_hash` VARCHAR(256) NOT NULL,
  `user_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jc_concepts`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jc_concepts`.`cart` (
  `user_id` INT NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_cart_product1_idx` (`product_id` ASC),
  INDEX `fk_cart_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_cart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `jc_concepts`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jc_concepts`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
